from tbpweb.achievements import course_file_achievements
from tbpweb.achievements import event_achievements
from tbpweb.achievements import meta_achievements
from tbpweb.achievements import officership_achievements
from tbpweb.achievements import pr_achievements
