# Generated by Django 2.2.8 on 2021-09-22 22:27

from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to=videos.models.Video.rename_file)),
                ('video_link', models.URLField(help_text='If the video cannot be hosted on another website such as Youtube, please contact IT to upload the video onto the TBP server.')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Term')),
                ('video_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.VideoType')),
            ],
            options={
                'unique_together': {('term', 'video_type')},
            },
        ),
    ]
