# Generated by Django 2.2.8 on 2021-09-22 22:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the meeting.', max_length=60)),
                ('date', models.DateField(default=datetime.date.today, help_text='Date the meeting was held.')),
                ('meeting_type', models.PositiveSmallIntegerField(choices=[(0, 'Officer Meeting'), (1, 'Executive Meeting'), (2, 'Other')])),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Term')),
            ],
            options={
                'verbose_name': 'minutes',
                'verbose_name_plural': 'minutes',
                'ordering': ('-date',),
            },
        ),
    ]
