# Generated by Django 2.2.8 on 2021-09-22 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the topic to be displayed on the page.', max_length=64)),
                ('icon', models.CharField(help_text="The name of the Font Awesome icon corresponding to this topic ('fa fa-' is implicitly included at the beginning).", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TimeInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the communication method to be displayed on the page.', max_length=64)),
                ('short_name', models.CharField(help_text='The name of the communication method to be displayed in checkboxes used for sorting.', max_length=64)),
                ('icon', models.CharField(help_text="The name of the Font Awesome icon corresponding to this topic ('fa fa-' is implicitly included at the beginning).", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('dream', models.TextField(blank=True, default='')),
                ('hobbies', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('college_activities', models.TextField(blank=True, default='')),
                ('discussion_topics', models.ManyToManyField(blank=True, related_name='_alumnus_discussion_topics_+', to='alumni.DiscussionTopic')),
                ('time_investment', models.ManyToManyField(blank=True, related_name='_alumnus_time_investment_+', to='alumni.TimeInvestment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
    ]
