language: python
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
script:
  - pipenv run python ./manage.py migrate
  - pipenv run python ./manage.py check