#!/bin/bash -e
export TBPWEB_MODE=production

if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then

  source "$HOME/.rvm/scripts/rvm"

elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then

  source "/usr/local/rvm/scripts/rvm"

else

  printf "ERROR: An RVM installation was not found.\n"

fi

# ==== OLD, replaced with HKN like settings
# cd ~/public_html/tbpweb
# rvm use
# source ~/public_html/tbpweb/.venv/bin/activate
# PYTHONPATH=~/public_html/tbpweb/src:$PYTHONPATH

# TODO ?
# DJANGO_SETTINGS_MODULE=tbpweb.settings
# DJANGO_WSGI_MODULE=tbpweb.wsgi

DJANGO_DIR=~/tbpweb/prod/current
VENV=~/tbpweb/prod/shared/venv
SOCKFILE=/srv/apps/$(whoami)/tbp.sock
NUM_WORKERS=4
PYTHONPATH=$DJANGO_DIR:$PYTHONPATH

cd $DJANGO_DIR
rvm use
source $VENV/bin/activate

exec gunicorn -w $NUM_WORKERS -b unix:$SOCKFILE \
    --log-file - settings.wsgi:application
