# Generated by Django 2.2.8 on 2021-09-22 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resumes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, help_text='GPA must have three decimal places (ex. 3.750)', max_digits=4, verbose_name='GPA')),
                ('full_text', models.TextField(help_text='Full text of the resume')),
                ('resume_file', models.FileField(help_text='PDF only please', upload_to=resumes.models.Resume.rename_file, verbose_name='File')),
                ('verified', models.NullBooleanField(choices=[(None, 'Pending'), (True, 'Approved'), (False, 'Denied')])),
                ('critique', models.BooleanField(default=True, help_text='Request an officer to critique your resume', verbose_name='Critique requested')),
                ('release', models.BooleanField(default=True, verbose_name='Release to companies')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_resumes', 'Can view all resumes'),),
            },
        ),
    ]
