# Generated by Django 2.2.8 on 2022-09-12 06:20

from django.db import migrations
import private_storage.fields
import private_storage.storage.files
import resumes.models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=private_storage.fields.PrivateFileField(help_text='PDF only please', storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=resumes.models.Resume.rename_file, verbose_name='File'),
        ),
    ]
