# Generated by Django 2.2.8 on 2021-09-22 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('mailing_list', models.CharField(blank=True, help_text='The mailing list name, not including the @domain.', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='HouseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.NullBooleanField(default=None, help_text='Is this person the house leader?')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housemember', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'term'), ('term', 'house', 'is_leader')},
            },
        ),
    ]
