# Generated by Django 2.2.8 on 2022-01-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LDAPUser',
        ),
    ]
