# Generated by Django 2.2.8 on 2022-09-12 06:20

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreport',
            name='attachment',
            field=private_storage.fields.PrivateFileField(blank=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='pr'),
        ),
        migrations.AlterField(
            model_name='projectreportbook',
            name='pdf',
            field=private_storage.fields.PrivateFileField(blank=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='project_report_books/'),
        ),
    ]
