# Generated by Django 2.2.8 on 2021-09-22 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=10)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(help_text='Full name for department (e.g. Computer Science)', max_length=100)),
                ('short_name', models.CharField(help_text='Colloquial shorthand for department (e.g. CS)', max_length=25, unique=True)),
                ('abbreviation', models.CharField(help_text='Standardized abbreviation for department from the registrar (e.g. COMPSCI)', max_length=25)),
                ('slug', models.SlugField(editable=False, max_length=25)),
            ],
            options={
                'ordering': ('long_name',),
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('website', models.URLField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Department')),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'middle_initial'),
                'unique_together': {('first_name', 'middle_initial', 'last_name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('instructors', models.ManyToManyField(to='courses.Instructor')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Term')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'number')},
        ),
    ]
