name: tbpweb-prod
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pypandoc
  - pdflatex
  - pip:
    - -r requirements.txt
    - mysqlclient==2.1.0
variables:
  TBPWEB_MODE: "production"
  DJANGO_SETTINGS_MODULE: "settings"
  DJANGO_WSGI_MODULE: "settings.wsgi"
