# Generated by Django 2.2.8 on 2022-09-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0002_auto_20220911_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='file_ext',
            field=models.CharField(help_text='File Ext with a period', max_length=5),
        ),
    ]
