# Generated by Django 2.2.8 on 2023-12-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_userprofile_alt_officer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alt_officer_email',
            field=models.CharField(blank=True, help_text='Set an alternate email on the Officers page. Don\'t include the domain name (".edu" or ".com") if obvious (to mitigate email scrapers). Leave blank to keep default tbp email (for officers only).', max_length=256, verbose_name='Alternate officer email address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other / Prefer Not to Say')], max_length=1),
        ),
    ]
