# Generated by Django 2.2.8 on 2021-09-22 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('negative', 'Negative'), ('neutral', 'Neutral'), ('positive', 'Positive')], max_length=8)),
                ('object_pk', models.PositiveIntegerField()),
                ('title', models.CharField(help_text='The title for describing the type of notification (e.g. "Achievement Unlocked" or "Missing Project Report").', max_length=128)),
                ('subtitle', models.CharField(help_text='The sub title for describing what the notification is associated with (e.g. an achievement name or project report title).', max_length=256)),
                ('description', models.CharField(help_text='The description for providing any additional information about the notification (e.g. how an achievement is unlocked or how long a project report is overdue).', max_length=512)),
                ('image_url', models.CharField(blank=True, help_text='The URL of any image for this notification (e.g. an achievement icon).', max_length=255)),
                ('url', models.CharField(blank=True, help_text='The URL that the user is redirected to when clicking the notification.', max_length=255)),
                ('cleared', models.BooleanField(db_index=True, default=False, help_text='Whether the user has closed this notification.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_pk')},
            },
        ),
    ]
