# Generated by Django 2.2.8 on 2023-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image_url',
            field=models.CharField(blank=True, help_text='The URL of any image for this notification (e.g. an achievement icon).', max_length=255, null=True),
        ),
    ]
